### ISSUE TITLE
Rate limit for exercise submissions

### ISSUE THREAD

**Issue by nygrenh** [rage/tmc-server#16]
- rack-throttle, 15 submissions per 10 minutes
- 250 per day [user_id] -> ban time 24h
- another limit for those with many submissions:
  * 3 per 10 minutes
   Lower submission priority
   Submission.where(created_at: (Time.now - 10.minutes)..Time.now, user: current_user).count

**Comment by Redande** [comment]
Rack-throttle: https://github.com/testmycode/tmc-server/commit/105d04082fc0f6f63159c9046872ad021ba21612
Low priority: https://github.com/testmycode/tmc-server/commit/75bf4f3c1105088469c243abd3f48da5347b07d2
